[versions]
android-compileSdk = "35"
android-targetSdk = "35"
android-minSdk = "21"

agp = "9.0.1"
kotlin = "2.3.10"
java-android = "17"
java-lint = "17"

androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
androidx-recyclerview = "1.4.0"
androidx-constraintlayout = "2.2.1"

junit4 = "4.13.2"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }

junit4 = { module = "junit:junit", version.ref = "junit4" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
